#Whether to replace the standard login and logout messages with custom ones
CustomMessageLoginLogout: true
MessageLogin: "#DDA0DD залетел на Сервер!"
MessageLogout: "#DDA0DD покинул этот мир!"

#Example for a PvP zone
RgWhiteList:
 0:
  minPos:
   x: -839
   y: 53
   z: -1445
  maxPos:
   x: -805
   y: 78
   z: -1388